version: 2.1
# orbs:
#   coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/python:3.9-node
        # environment:
        # PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v2-platformio-v10-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "platformio.ini" }}-{{ checksum ".circleci/config.yml" }}
            - v2-platformio-v10-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "platformio.ini" }}
            - v2-platformio-v10-{{ .Branch }}-{{ checksum "Pipfile" }}-
            - v2-platformio-v10-{{ .Branch }}-
            - v2-platformio-v10-
      - run:
          name: Set up
          command: |
            sudo apt update
            pip install --upgrade pipenv
            pipenv --python 3 install
            pipenv run pio update
            pipenv run pio platform install native
      - run:
          name: Build
          command: |
            pipenv run pio run -e ecu -e motor -e power_aux -e solar
      # - run:
      #     name: Test
      #     command: |
      #       pipenv run pio test -e native
      # Disable linting because this uses ~8 minutes of CircleCI time
      # - run:
      #     name: Lint
      #     command: |
      #       sudo apt install -y libtinfo5
      #       pipenv run pio check --fail-on-defect high -e native
      # Disable code coverage checks since we are no longer aiming for 100% coverage
      # - run:
      #     name: Coverage
      #     command: |
      #       mkdir -p .coverage/input .coverage/output
      #       shopt -s globstar
      #       cp .pio/**/*.gcno .coverage/input || :
      #       cp .pio/**/*.gcda .coverage/input || :
      #       pipenv run gcovr -e Common/lib/FakeIt/ -e Common/lib/MbedMock/ -e test/ --html-details -o .coverage/output/coverage.html
      #       sudo apt install lcov
      #       lcov --capture --base-directory . --directory . --no-external --exclude "*/Common/lib/FakeIt/*" --exclude "*/Common/lib/MbedMock/*" --exclude "*/test/*" --output-file .coverage/input/coverage.info
      - save_cache:
          paths:
            # - ~/.local/share/virtualenvs # Disabled because caching this causes issues when Python minor version updates occur
            - ~/.platformio/cache
            # - .coverage
          key: v2-platformio-v10-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "platformio.ini" }}-{{ checksum ".circleci/config.yml" }}
      # - store_artifacts:
      #     path: .coverage/output
      # - coveralls/upload:
      #     path_to_lcov: .coverage/input/coverage.info
